version: '3'
services:
  keto-migrate:
    image: oryd/keto:v0.12.0-alpha.0
    links:
      - postgresql:postgresql
    volumes:
      - type: bind
        source: ./rules
        target: /home/ory
    environment:
      - LOG_LEVEL=debug
      - DSN=postgres://postgres:postgres@postgresql:5432/seminar?sslmode=disable
    command: ["migrate", "up", "-y"]
    restart: on-failure
  keto:
    image: oryd/keto:v0.11.1-alpha.0
    links:
      - postgresql:postgresql
    volumes:
      - type: bind
        source: ./rules
        target: /home/ory
    ports:
      - "4466:4466"
      - "4467:4467"
    depends_on:
      - keto-migrate
    environment:
      - DSN=postgres://postgres:postgres@postgresql:5432/seminar?sslmode=disable
    restart: on-failure
  postgresql:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seminar
  oathkeeper:
    image: oryd/oathkeeper:v0.38.2
    ports:
      - "4455:4455"
    environment:
      - LOG_LEVEL=debug
      - DSN=memory
      - ACCESS_RULES_PATH=/rules/access-rules.yml
    volumes:
      - ./rules:/rules
    command: serve
